# Other values include trace, debug, warn and error
log-filter = "info"

# the server will get its time from the NTP pool
[[peers]]
mode = "pool"
address = "pool.ntp.org"
count = 4

[[server]]
listen = "0.0.0.0:123"

# to function as an NTS server, we must also provide key exchange
[nts-ke-server]
addr = "0.0.0.0:4460"
cert-chain-path = "path/to/certificate/chain.pem"
key-der-path = "path/to/private.key"
timeout-ms = 1000
