#!/bin/sh
set -e

NTPDRS_CONF="/etc/ntpd-rs/ntp.toml"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -f ${NTPDRS_CONF} ]; then
        rm ${NTPDRS_CONF}
    fi
    ;;
esac

#DEBHELPER#
