#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
    deb-systemd-invoke stop ntpd-rs.service >/dev/null || true
    deb-systemd-invoke stop ntpd-rs-metrics.service >/dev/null || true
fi
