[package]
name = "statime-algo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
arrayvec.workspace = true
libm.workspace = true
statime-base.workspace = true

[features]
default = ["std"]
std = ["statime-base/std"]

# Ignore unused libm, as it is needed for polyfilling when std is not used.
[package.metadata.cargo-udeps]
ignore = [["libm"]]
