post_install_script = '''
#!/bin/bash -e
#RPM_SYSTEMD_MACROS#

if [ $EUID -ne 0 ]; then
    echo >&2 "ERROR: ntpd-rs postinst script must be run as root"
    exit 1
fi

NTPDRS_USER=ntpd-rs
NTPDRS_OBSERVE_USER=ntpd-rs-observe
NTPDRS_HOME_DIR="/var/lib/ntpd-rs"
NTPDRS_OBSERVE_HOME_DIR="/var/lib/ntpd-rs-observe"
NTPDRS_HOME_DIR_PERMS=700
NTPDRS_CONF_SRC="/usr/share/doc/ntpd-rs/ntp.toml.default"
NTPDRS_CONF_DIR="/etc/ntpd-rs"
NTPDRS_CONF="${NTPDRS_CONF_DIR}/ntp.toml"
NTPDRS_CONF_PERMS=644

create_user() {
    if ! id ${NTPDRS_USER} > /dev/null 2>&1; then
        # According to the CentOS 7 useradd man page:
        # --user-group causes a group by the same name as the user to be created
        # --create-home should force creation of a home dir even for a system account.
        useradd --home-dir ${NTPDRS_HOME_DIR} --system --create-home --user-group ${NTPDRS_USER}
    fi
    if ! id ${NTPDRS_OBSERVE_USER} > /dev/null 2>&1; then
        useradd --home-dir ${NTPDRS_OBSERVE_HOME_DIR} --system --create-home --user-group ${NTPDRS_OBSERVE_USER}
    fi
    # Ensure that the home directory has the correct ownership
    chown -R ${NTPDRS_USER}:${NTPDRS_USER} ${NTPDRS_HOME_DIR}
    chown -R ${NTPDRS_OBSERVE_USER}:${NTPDRS_OBSERVE_USER} ${NTPDRS_OBSERVE_HOME_DIR}
    # Ensure that the home directory has the correct permissions
    chmod ${NTPDRS_HOME_DIR_PERMS} ${NTPDRS_HOME_DIR}
    chmod ${NTPDRS_HOME_DIR_PERMS} ${NTPDRS_OBSERVE_HOME_DIR}
}

init_systemd_service() {
    systemd_post ntpd-rs.service
    systemd_post ntpd-rs-metrics.service
    systemd_triggers
}

link_man_page() {
    if [ ! -f "/usr/share/man/man5/ntp.toml.5" ]; then
        (cd "/usr/share/man/man5" && ln -s "ntp-toml.5" "ntp.toml.5")
    fi
}

if [ $1 -eq 1 ] ; then
    # Initial installation
    create_user
    link_man_page
    init_systemd_service
fi
'''

pre_uninstall_script = '''
#!/bin/bash -e
#RPM_SYSTEMD_MACROS#

if [ $1 -eq 0 ] ; then
    # Package removal, not upgrade
    # Run commands equivalent to what the RPM systemd macros would do
    systemd_preun ntpd-rs.service
    systemd_preun ntpd-rs-metrics.service
    systemd_triggers
fi
'''

post_uninstall_script = '''
#!/bin/bash -e
#RPM_SYSTEMD_MACROS#

if [ $1 -ge 1 ] ; then
    # Run commands equivalent to what the RPM systemd macros would do
    systemd_postun_with_restart ntpd-rs.service
    systemd_postun_with_restart ntpd-rs-metrics.service
    systemd_triggers
fi
'''
