[observability]
# Other values include trace, debug, warn and error
log-level = "info"
observation-path = "/run/ntpd-rs/observe"

# uses an unsecure certificate!
[[peer]]
mode = "nts"
address =  "localhost:4460"
certificates = "test-keys/testca.pem"

# System parameters used in filtering and steering the clock:
[synchronization]
min-intersection-survivors = 1
single-step-panic-threshold = 10
startup-step-panic-threshold = { forward = "inf", backward = 86400 }
