[observability]
# Other values include trace, debug, warn and error
log-level = "info"
observation-path = "/run/ntpd-rs/observe"

# the server will get its time from the NTP pool
[[peer]]
mode = "pool"
address = "pool.ntp.org"
count = 4

[[server]]
listen = "0.0.0.0:123"

# System parameters used in filtering and steering the clock:
[synchronization]
minimum-agreeing-peers = 1
single-step-panic-threshold = 10
startup-step-panic-threshold = { forward = 0, backward = 86400 }

# to function as an NTS server, we must also provide key exchange
# uses an unsecure certificate chain!
[[nts-ke-server]]
key-exchange-listen = "0.0.0.0:4460"
certificate-chain-path = "test-keys/end.fullchain.pem"
private-key-path = "test-keys/end.key"
key-exchange-timeout-ms = 1000
