[logging-observability]
# Other values include trace, debug, warn and error
log-level = "info"
observation-path = "/run/ntpd-rs/observe"

# uses an unsecure certificate!
[[peers]]
mode = "nts"
address =  "localhost:4460"
certificate = "test-keys/testca.pem"

# System parameters used in filtering and steering the clock:
[system]
min-intersection-survivors = 1
panic-threshold = 10
startup-panic-threshold = { forward = "inf", backward = 1800 }