[package]
name = "statime-seccomp"
license = "Apache-2.0 OR MIT"
version = "1.0.0-testing.1"
edition = "2024"
readme = "./NOTICE.md"
descriptione = "Minimalist seccomp filter for statime"
publish = true
rust-version = "1.95" # MSRV

[lints.rust]
missing_docs = "deny"

[features]
default = []

[dependencies]

[build-dependencies]
# we cannot simply use cc = "1" here, since that will cause the minimal version check to fail due to
# other dependencies also depending on cc
cc = "1.0.100"
