[package]
name = "statime-seccomp"
license.workspace = true
version = "1.0.0-testing.1"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]

[build-dependencies]
# we cannot simply use cc = "1" here, since that will cause the minimal version check to fail due to
# other dependencies also depending on cc
cc = "1.0.100"
