name: nightly

permissions: {}

on:
  push:
    branches:
      - 'release/**'
      - 'debug-freebsd'
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: {}

jobs:
  test-freebsd:
    # see https://github.com/actions/runner/issues/385
    # use https://github.com/vmactions/freebsd-vm for now
    name: test on freebsd
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - name: test on freebsd
        uses: vmactions/freebsd-vm@a6de9343ef5747433d9c25784c90e84998b9d69a
        with:
          usesh: true
          mem: 4096
          copyback: false
          prepare: |
            pkg install -y curl cmake llvm-devel
            curl https://sh.rustup.rs -sSf --output rustup.sh
            sh rustup.sh -y --profile minimal --default-toolchain stable
            . "$HOME/.cargo/env"
            rustup component add clippy
            echo "~~~~ rustc --version ~~~~"
            rustc --version
            echo "~~~~ freebsd-version ~~~~"
            freebsd-version
          run: |
            . "$HOME/.cargo/env"
            cargo clippy --workspace --all-targets -- -D warnings &&
            cargo build --all-targets &&
            cargo test
